drop database if exists aviation with (force);

-- Crée une nouvelle base nommée aviation.
create database aviation owner aviation;

-- Extension spatiale qui ajoute des types géométriques, index spatiaux et fonctions géographiques.
-- Ne pas placer l'extension dans un schéma séparé car l'ORM Doctrine ne retouve pas les fonctions
create extension if not exists postgis;

-- Extension qui fournit des opérateurs B-tree compatibles avec les index complexes GiST
create extension if not exists btree_gist;

\c aviation;

set role cocagne;

-- ICAO Organisation de l'aviation civile internationale
-- IATA Association du transport aérien international

create table aviation.aeroports (
  aeroport_code_icao text,
  aeroport_code_iata text,
  nom text,
  ville text,
  pays text,
  altitude int,
  tz text,
  coordonnees geometry(Point, 4326) default null::geometry
);

create unique index aeroports_aeroport_code_iata_idx
  on aviation.aeroports (aeroport_code_iata);

alter table aviation.aeroports
  add primary key using index aeroports_aeroport_code_iata_idx;

alter table only aviation.aeroports
  add foreign key (pays)
  references pays (code2);

create table aviation.appareils (
  type text,
  msn text,
  immatriculation text,
  hexa text,
  livraison date,
  nom text
);

create table aviation.operateurs (
  operateur_code_icao text,
  operateur_code_iata text,
  operateur text,
  callsign text
);

create unique index operateurs_operateur_code_iata_idx
  on aviation.operateurs (operateur_code_iata);

alter table aviation.operateurs
  add primary key using index operateurs_operateur_code_iata_idx;

create table aviation.modeles (
  code_iata text not null,
  modele text,
  constructeur character(2),
  code_icao character(4),
  code_famille character(3),
  wtc character(1),
  pax integer,
  speed integer,
  ceiling integer,
  range integer,
  mtow integer,
  mlw integer
);

-- A transformer en json

comment on column aviation.modeles.wtc IS 'Wake Turbulence Category';
comment on column aviation.modeles.pax IS 'Passengers : nombre de passager en configuration standard 3 classes';
comment on column aviation.modeles.speed IS 'kts (noeuds)';
comment on column aviation.modeles.ceiling IS 'ft (pieds)';
comment on column aviation.modeles.range IS 'nautical mile (milles nautiques)';
comment on column aviation.modeles.mtow IS 'lbs Maximum Take-Off Weight';
comment on column aviation.modeles.mlw IS 'lbs Maximum Landing Weight';


create table aviation.vols (
  vol_id integer not null,
  jour date,
  operateur_code_iata text,
  vol_numero int,
  appareil_code text,
  origine text,
  destination text,
  distance int,
  fuseau_horaire_origine text,
  fuseau_horaire_destination text,
  heure_prevue_depart timestamp with time zone null,
  delais_depart int,
  heure_depart timestamp with time zone null,
  roulage_depart int,
  decollage timestamp with time zone null,
  duree_vol int,
  atterrissage timestamp with time zone null,
  roulage_arrivee int,
  heure_arrivee timestamp with time zone null,
  delais_arrivee int,
  heure_prevue_arrivee timestamp with time zone null,
  duree_prevue int,
  duree int,
  derouté int,
  annulé int,
  annulation_raison text,
  delais_du_control_aerien int,
  delais_du_securite int,
  delais_du_operateur int,
  delais_du_avion int,
  delais_du_meteo int
);

alter table aviation.vols
  alter column vol_id
  add generated by default as identity;

create unique index vols_pk
  on aviation.vols
  using btree (vol_id);

alter table aviation.vols
  add primary key using index vols_pk;

select '=============== FIN STRUCTURE Aviation' as msg;


alter table aviation.vols
  add foreign key (operateur_code_iata) references aviation.operateurs;

-- Derivative work from Our Airports
-- https://github.com/davidmegginson/ourairports-data

create temporary table operateurs_tmp (
  AirlineID int,
  Name text,
  Alias text,
  IATA text,
  ICAO text,
  Callsign text,
  Country text,
  Active text
);

\copy operateurs_tmp from './operateurs.csv' (format csv, header, encoding 'utf8');

insert into aviation.operateurs (
  operateur_code_icao,
  operateur_code_iata,
  operateur,
  callsign
)
select ICAO, IATA, Name, upper(Callsign) from operateurs_tmp
  where Active = 'Y' and IATA <> '' and ICAO <> 'N/A' and ICAO <> '\N' and ICAO <> '';

--

create temporary table aeroports_tmp (
  AirportID integer,
  name text,
  City text,
  Country text,
  IATA text,
  ICAO text,
  latitude decimal(18, 15),
  longitude decimal(18, 15),
  altitude int,
  Timezone text,
  DST text,
  TZ text,
  Type text,
  Source text
);

\copy aeroports_tmp from './aeroports.csv' (FORMAT CSV, header, delimiter ',', ENCODING 'UTF8');

-- Corriger les noms des pays
update aeroports_tmp set Country = 'United States of America' WHERE Country = 'United States';
update aeroports_tmp set Country = 'Republic of Korea' WHERE Country = 'South Korea';
update aeroports_tmp set Country = 'Myanmar' WHERE Country = 'Burma';
update aeroports_tmp set Country = 'United Kingdom of Great Britain and Northern Ireland' WHERE Country = 'United Kingdom';
update aeroports_tmp set Country = 'Iran (Islamic Republic of)' WHERE Country = 'Iran';
update aeroports_tmp set Country = 'Venezuela (Bolivarian Republic of)' WHERE Country = 'Venezuela';
update aeroports_tmp set Country = 'Bolivia (Plurinational State of)' WHERE Country = 'Bolivia';
update aeroports_tmp set Country = 'Viet Nam' WHERE Country = 'Vietnam';
update aeroports_tmp set Country = 'Côte d''Ivoire' WHERE Country = 'Cote d''Ivoire';
update aeroports_tmp set Country = 'Czechia' WHERE Country = 'Czech Republic';
update aeroports_tmp set Country = 'Congo' WHERE Country = 'Congo (Kinshasa)';
update aeroports_tmp set Country = 'United Republic of Tanzania' WHERE Country = 'Tanzania';

-- Supprimer les enregistrements sans code IATA
update aeroports_tmp set IATA = null where iata = '\N';
-- \copy (select * from aeroports_tmp where IATA is null) to '/data/aviation/aeroports-iata-null.csv' (FORMAT CSV, header, delimiter ',', ENCODING 'UTF8');
delete from aeroports_tmp where IATA is null;

-- Copier les données dans la table aviation.aeroports
insert into aviation.aeroports (aeroport_code_icao, aeroport_code_iata, nom, ville, pays, altitude, tz, coordonnees)
  select ICAO, IATA, name, City, pays.code2, altitude, TZ, st_makepoint(longitude, latitude)
  from aeroports_tmp
  left join pays on (pays.nom_eng = aeroports_tmp.Country)
  where IATA is not null
  order by AirportID;

drop table aeroports_tmp;


-- https://www.kaggle.com/datasets/usdot/flight-delays

set timezone = 'UTC';

create table aviation.vols_tmp (
  YEAR int,                 -- 2015 (jour)
  MONTH int,                -- 1    (jour)
  DAY int,                  -- 1    (jour)
  DAY_OF_WEEK int,          -- 4    (jour)
  AIRLINE text,             -- AA   (operateur_code_iata)
  FLIGHT_NUMBER int,        -- 1057 (vol_numero)
  TAIL_NUMBER text,         -- N3ASAA (appareil_code)
  ORIGIN_AIRPORT text,      -- DFW  (origine)
  DESTINATION_AIRPORT text, -- MIA  (destination)
  SCHEDULED_DEPARTURE text, -- 0515 (heure_prevue_depart)
  DEPARTURE_TIME text,      -- 0703 (heure_depart),
  DEPARTURE_DELAY int,      -- 108  (delais_depart)
  TAXI_OUT int,             -- 15,  (roulage_depart)
  WHEELS_OFF TEXT,          -- 0718 (decollage)
  SCHEDULED_TIME int,       -- 161,   (temps_prevu)
  ELAPSED_TIME int,         -- 155,   (temps)
  AIR_TIME int,             -- 133,   (temps_en_vol)
  DISTANCE int,             -- 1121,  (distance)
  WHEELS_ON text,           -- 1031   (atterrissage)
  TAXI_IN int,              -- 7      (roulage_arrivee)
  SCHEDULED_ARRIVAL text,   -- 0856   (heure_prevue_arrivee)
  ARRIVAL_TIME text,        -- 1038,  (heure_arrivee)
  ARRIVAL_DELAY int,        -- 102,   (delais_arrivee)
  DIVERTED int,             -- 0,
  CANCELLED int,            -- 0,
  CANCELLATION_REASON text, -- ,
  AIR_SYSTEM_DELAY int,     -- 0,
  SECURITY_DELAY int,       -- 0,
  AIRLINE_DELAY int,        -- 0,
  LATE_AIRCRAFT_DELAY int,  -- 0
  WEATHER_DELAY int         -- ,102
  );

\copy aviation.vols_tmp from './flights2.csv' (format csv, header, encoding 'utf8');

ALTER TABLE aviation.vols_tmp
  ADD COLUMN TS_SCHEDULED_DEPARTURE timestamp WITH TIME ZONE NULL,
  ADD COLUMN TS_DEPARTURE_TIME timestamp WITH TIME ZONE NULL,
  ADD COLUMN TS_WHEELS_OFF timestamp WITH TIME ZONE NULL,
  ADD COLUMN TS_WHEELS_ON timestamp WITH TIME ZONE NULL,
  ADD COLUMN TS_SCHEDULED_ARRIVAL timestamp WITH TIME ZONE NULL,
  ADD COLUMN TS_ARRIVAL_TIME timestamp WITH TIME ZONE NULL,
  ADD COLUMN TZ_ORIGIN text NULL,
  ADD COLUMN TZ_DESTINATION text NULL;

-- Recopier le fuseau horaire
UPDATE aviation.vols_tmp SET
TZ_ORIGIN = a.TZ FROM aviation.aeroports a WHERE a.aeroport_code_iata = vols_tmp.origin_airport;

UPDATE aviation.vols_tmp SET
TZ_DESTINATION = a.TZ FROM aviation.aeroports a WHERE a.aeroport_code_iata = vols_tmp.destination_airport;

UPDATE aviation.vols_tmp SET TS_SCHEDULED_DEPARTURE = TO_TIMESTAMP(
    LPAD(YEAR::text, 4, '0') || '-' ||
    LPAD(MONTH::text, 2, '0') || '-' ||
    LPAD(DAY::text, 2, '0') || ' ' ||
    LPAD(SUBSTRING(SCHEDULED_DEPARTURE, 1, 2), 2, '0') || ':' ||
    LPAD(SUBSTRING(SCHEDULED_DEPARTURE, 3, 2), 2, '0'),
    'YYYY-MM-DD HH24:MI'
  )::timestamp at time zone TZ_ORIGIN;

UPDATE aviation.vols_tmp
  SET TS_DEPARTURE_TIME = (TS_SCHEDULED_DEPARTURE at time zone TZ_ORIGIN + (DEPARTURE_DELAY * interval '1 minute'))::timestamp at time zone TZ_ORIGIN,
  TS_SCHEDULED_ARRIVAL = (TS_SCHEDULED_DEPARTURE at time zone TZ_ORIGIN + (SCHEDULED_TIME * interval '1 minute'))::timestamp at time zone TZ_ORIGIN;

UPDATE aviation.vols_tmp
  SET TS_WHEELS_OFF = (TS_DEPARTURE_TIME at time zone TZ_ORIGIN + (TAXI_OUT * interval '1 minute'))::timestamp at time zone TZ_ORIGIN,
  TS_ARRIVAL_TIME = ((TS_DEPARTURE_TIME at time zone TZ_ORIGIN + (ELAPSED_TIME * interval '1 minute'))::timestamp at time zone TZ_ORIGIN) at time zone TZ_DESTINATION;

UPDATE aviation.vols_tmp
  SET TS_WHEELS_ON = ((TS_WHEELS_OFF at time zone TZ_ORIGIN + (AIR_TIME * interval '1 minute'))::timestamp at time zone TZ_ORIGIN) at time zone TZ_DESTINATION;

insert into aviation.vols (jour,
  operateur_code_iata, vol_numero, appareil_code,
  origine, destination, distance,
  fuseau_horaire_origine, fuseau_horaire_destination,
  heure_prevue_depart, delais_depart, heure_depart,
  duree_prevue, duree,
  heure_prevue_arrivee, delais_arrivee, heure_arrivee,
  roulage_depart, roulage_arrivee,
  decollage, duree_vol, atterrissage,
  derouté,
  annulé,
  annulation_raison,
  delais_du_control_aerien,
  delais_du_securite,
  delais_du_operateur,
  delais_du_avion,
  delais_du_meteo
  )
select
  to_date(
    LPAD(YEAR::text, 4, '0') || '-' ||
    LPAD(MONTH::text, 2, '0') || '-' ||
    LPAD(DAY::text, 2, '0'),
    'YYYY-MM-DD'
  ),
  AIRLINE,
  FLIGHT_NUMBER,
  TAIL_NUMBER,
  ORIGIN_AIRPORT, DESTINATION_AIRPORT, DISTANCE,
  TZ_ORIGIN, TZ_DESTINATION,
  to_timestamp(
    LPAD(YEAR::text, 4, '0') || '-' ||
    LPAD(MONTH::text, 2, '0') || '-' ||
    LPAD(DAY::text, 2, '0') || ' ' ||
    LPAD(SUBSTRING(SCHEDULED_DEPARTURE, 1, 2), 2, '0') || ':' ||
    LPAD(SUBSTRING(SCHEDULED_DEPARTURE, 3, 2), 2, '0'),
    'YYYY-MM-DD HH24:MI'
  )::timestamp at time zone TZ_ORIGIN,
  DEPARTURE_DELAY,
  (TS_SCHEDULED_DEPARTURE at time zone TZ_ORIGIN + (DEPARTURE_DELAY * interval '1 minute'))::timestamp at time zone TZ_ORIGIN,
  SCHEDULED_TIME, ELAPSED_TIME,
  (TS_SCHEDULED_DEPARTURE at time zone TZ_ORIGIN + (SCHEDULED_TIME * interval '1 minute'))::timestamp at time zone TZ_ORIGIN,
  ARRIVAL_DELAY,
  (TS_DEPARTURE_TIME at time zone TZ_ORIGIN + (ELAPSED_TIME * interval '1 minute'))::timestamp at time zone TZ_ORIGIN,
  TAXI_OUT, TAXI_IN,
  (TS_DEPARTURE_TIME at time zone TZ_ORIGIN + (TAXI_OUT * interval '1 minute'))::timestamp at time zone TZ_ORIGIN,
  AIR_TIME,
  (TS_WHEELS_OFF at time zone TZ_ORIGIN + (AIR_TIME * interval '1 minute'))::timestamp at time zone TZ_ORIGIN,
  DIVERTED,
  CANCELLED,
  CANCELLATION_REASON,
  AIR_SYSTEM_DELAY,
  SECURITY_DELAY,
  AIRLINE_DELAY,
  LATE_AIRCRAFT_DELAY,
  WEATHER_DELAY
from aviation.vols_tmp;

-- Modeles

create temporary table modeles_tmp (
  Aircraft_type_ID text,
  Manufacturer_name text,
  Aircraft_type_name text,
  ICAO_aircraft_type_designator text,
  Manufacturer_country text,
  Category text,
  Role text,
  Engine_type text,
  Engines text,
  WTC text,
  Seats text,
  First_flight text,
  Last_manufactured text,
  Total_built text
);


\copy aviation.appareils from './appareils.csv' (format csv, header, encoding 'utf8');
