\pset tuples_only on

drop database if exists cinema with (force);

-- Crée une nouvelle base nommée cinema.
create database cinema owner cinema;

-- Contrôle l’ordre de résolution des schémas.
alter database cinema set search_path = public,extensions;

\c cinema;

-- Extensions

create schema extensions authorization pg_database_owner;

create extension postgis schema extensions;

create extension fuzzystrmatch schema extensions;

-- Données générales
-- --------------------------------------------------------------------------------

create table pays (
  code text not null,
  pays text not null,
  drapeau_unicode text
);

comment on column pays.code
  is 'code ISO 3166-1 alpha 2';

create index pays_nom
  on pays using btree (pays asc nulls last);

alter table pays
  add check (code ~ '^[a-z]{2}$');

create unique index pays_pk
  on pays
  using btree (code);

alter table pays
  add primary key using index pays_pk;

create temporary table pays_import
(
  code2 text,
  code3 text,
  code_num text,
  pays text,
  tncc smallint,
  drapeau_unicode text,
  forme_longue text,
  independant boolean,
  communautaire boolean,
  sepa boolean,
  telephone smallint
);

copy pays_import
from '/tmp/commun/pays.csv' (format csv, header, encoding 'UTF8');

insert into pays
select lower(code2), pays, drapeau_unicode
from pays_import;

--

create table langues (
  code3 char(3) not null,
  langue text default null,
  francais text default null
);

comment on table langues is 'ISO 639-3';

alter table langues
  add check (code3 ~ '^[a-z]{3}$');

create unique index langues_pk
  on langues
  using btree (code3);

alter table langues
  add primary key using index langues_pk;

copy langues
from '/tmp/cinema/003-langues.csv' (FORMAT CSV, header, delimiter ',', ENCODING 'UTF8');


/*
alter default privileges
  for role postgres
  in schema cinema
  grant insert, select, update, delete on tables to iutsd;
*/

-- Personnes

create table personnes (
  personne_id int not null,
  nom text,
  prenom text,
  naissance date,
  deces date,
  nationalite text,
  artiste text,
  popularite decimal default 0
);

alter table personnes
  add constraint personne_naissance
  check (naissance > '1730-01-01') not valid;

alter table personnes
  add constraint personne_deces
  check (deces > naissance) not valid;

alter table personnes
  add constraint personne_nationalite
  check (char_length(nationalite) = 2) not valid;

create unique index personnes_unique
  on personnes using btree (nom, prenom);

alter table personnes
  add constraint personnes_unique unique
  using index personnes_unique;

-- Clé primaire auto incrément

alter table personnes
  alter column personne_id
  add generated by default as identity;

create unique index personnes_pk
  on personnes
  using btree (personne_id);

alter table personnes
  add primary key using index personnes_pk;

--

alter table personnes
  add column created_at timestamp with time zone default now(),
  add column updated_at timestamp with time zone;

-- Sociétés

create table societes (
  societe_id int not null,
  societe text not null,
  uei text
);

comment on column societes.uei is 'Unique Entity ID';

alter table societes
  alter column societe_id
  add generated by default as identity;

alter table societes
  add primary key (societe_id);

-- A transformer en table

create type role as enum (
  'acteur',
  'voix',
  'réalisateur',
  'scénariste',
  'musique',
  'roman'
);

create table etablissements (
  etablissement_id integer not null,
  nom text,
  voie text,
  codepostal text,
  ville text,
  ecrans smallint,
  fauteuils smallint,
  coordonnees geometry(Point, 4326) default null::geometry,
  constraint cinema_pkey primary key (etablissement_id)
);

create index cinema_coordonnees_idx
  on etablissements
  using GIST (coordonnees);

alter table etablissements
  add column created_at timestamp with time zone default now(),
  add column updated_at timestamp with time zone;

create table series (
  serie_id integer not null,
  serie text not null
);

alter table series
  alter column serie_id
  add generated by default as identity;

alter table series
  add primary key (serie_id);


create table films (
  film_id int not null,
  titre text not null,
  titre_original text,
  annee integer,
  sortie date,
  duree integer,
  serie_id integer,
  slogan text,
  pays text[],
  created_at   timestamp(0) with time zone default current_timestamp not null,
  updated_at   timestamp(0) with time zone default NULL::timestamp(0) with time zone
);

alter table films
  alter column film_id
  add generated by default as identity;

alter table films
  add primary key (film_id);

alter table films
  add foreign key (serie_id)
    references series match simple
    on update no action
    on delete no action
    not valid;


create table motscles (
  motcle_id integer primary key,
  motcle text not null
);

create table films_motscles (
  film_id int not null,
  motcle_id integer not null
);

-- films_motscles -> films

create unique index film_motscles_pkey
  on films_motscles
  using btree (film_id, motcle_id);

alter table films_motscles
  add primary key
  using index film_motscles_pkey;

create index film_motscles_films
  on films_motscles
  using btree (film_id);

-- films_motscles -> motscles

create index film_motscles_motscles
  on films_motscles
  using btree (motcle_id);

alter table films_motscles
  add foreign key (film_id)
  references films(film_id)
  on delete cascade;


alter table films_motscles
  add foreign key (motcle_id)
  references motscles(motcle_id)
  on delete cascade;

-- Genres

create table genres (
  genre_id integer not null,
  genre text not null
);

-- Clé primaire auto incrément

alter table genres
  alter column genre_id
  add generated by default as identity;

create unique index genres_pk
  on genres
  using btree (genre_id);

alter table genres
  add primary key using index genres_pk;

create table equipes (
  film_id int not null,
  personne_id int not null,
  role role,
  alias text,
  ordre int2 null default 99
);

comment on table equipes is
  e'@foreignkey (personne) references acteur(id)|@fieldname rolebyacteur';


/*
constraint equipe_film_fk foreign key (film) references films(id)
    on update no action on delete no action not valid,
  constraint equipe_personne_fk foreign key (personne) references personnes(id)
    on update no action on delete no action not valid
*/

-- equipes -> films
create index on equipes(film_id);

alter table equipes
add foreign key (film_id)
  references films
  on delete cascade;

-- equipes -> personnes
create index on equipes(personne_id);

alter table equipes
add foreign key (personne_id)
  references personnes
  on delete cascade;

comment on table equipes is
  e'@foreignkey (personne) references acteur(id)|@fieldname rolebyacteur';

create table films_genres (
  film_id int not null,
  genre_id integer not null
);

create unique index film_genres_pkey
  on films_genres
  using btree (film_id, genre_id);

alter table films_genres
  add primary key
  using index film_genres_pkey;

-- films_genres -> films
create index on films_genres(film_id);

alter table films_genres
add foreign key (film_id)
  references films(film_id)
  on delete cascade;

-- films_genres -> genres
create index on films_genres(genre_id);

alter table films_genres
add foreign key (genre_id)
  references genres(genre_id)
  on delete cascade;


-- Productions

create table productions (
  film_id int not null,
  societe_id int not null
);

create index on productions
  using btree (film_id);

create index on productions
  using btree (societe_id);

alter table productions
  add primary key (film_id, societe_id);

alter table productions
add constraint productions_film_id_fkey
  foreign key (film_id) references films(film_id)
  on delete cascade;

alter table productions
add constraint productions_societe_id_fkey
  foreign key (societe_id) references societes(societe_id)
  on delete cascade;


-- sites

create table sites (
  site_id smallint not null,
  site text not null,
  url text not null
);

alter table sites
  add primary key (site_id);

insert into sites values
  (1,'TMDB (The Movie Database)','https://www.themoviedb.org/movie/$id'),
  (2,'IMDb (Internet Movie Database)','https://www.imdb.com/title/$id'),
  (3,'Wikipedia','https://fr.wikipedia.org/wiki/$id'),
  (4,'YouTube','https://youtu.be/$id'),
  (5,'Sens Critique','https://www.senscritique.com/film/_/$id'),
  (6,'AlloCiné','https://www.allocine.fr/film/fichefilm_gen_cfilm=$id.html');

create table links (
  id int not null,
  site_id smallint not null,
  identifiant text not null
);

alter table links
  add constraint links_no_insert_in_parent
  check (false) no inherit;

alter table links
  add primary key (id, site_id);

create table links_films (
) inherits (links);

create table links_personnes (
) inherits (links);

alter table links_films
  add primary key (id, site_id);

alter table links_personnes
  add primary key (id, site_id);

create index links_films_id
  on links_films(id);

create index links_films_site
  on links_films(site_id);

alter table links_films
  add foreign key (id)
  references films(film_id)
  on delete cascade;

alter table links_films
add foreign key (site_id)
  references sites
  on delete cascade;

-- Links Personnes

create index links_personnes_id
  on links_personnes(id);

create index links_personnes_site
  on links_personnes(site_id);

alter table links_personnes
  add foreign key (id)
  references personnes(personne_id)
  on delete cascade;

alter table links_personnes
add foreign key (site_id)
  references sites
  on delete cascade;

create table salles (
  salle_id integer not null,
  etablissement_id integer not null,
  salle text not null,
  sieges integer not null
);

alter table salles
  add primary key (salle_id);

alter table salles
  add foreign key (etablissement_id) references etablissements
  on delete cascade;


-- seances

create table seances (
  seance_id int not null,
  film_id int not null,
  salle_id int not null,
  seance date not null
);


alter table seances
  alter column seance_id
  add generated by default as identity;

create index on seances
  using btree (film_id);

create index on seances
  using btree (salle_id);

alter table seances
  add primary key (seance_id);

alter table seances
add foreign key (film_id) references films
  on delete cascade;

alter table seances
  add foreign key (salle_id) references salles;

create table resumes (
  film_id int not null,
  langue text not null,
  resume text not null
);

alter table resumes
  add column ts tsvector
  generated always as (to_tsvector('french', resume)) stored;

CREATE INDEX resume_texte_idx
  ON resumes USING GIN(ts);

-- Clé primaire composée

create unique index resumes_pk
  on resumes
  using btree (film_id, langue);

alter table resumes
  add primary key using index resumes_pk;

create index resume_film_fki
  on resumes(film_id);

-- Clé étrangère

alter table resumes
  add FOREIGN KEY (film_id)
  references films on delete cascade;

alter table resumes
  add FOREIGN KEY (langue)
  references langues (code3);


-- SELECT * from resume WHERE ts @@ to_tsquery('french', 'romancier');

create table certifications (
  pays_code text not null,
  ordre smallint,
  certification text not null,
  description text
);

create unique index certifications_pk
  on certifications
  using btree (pays_code, certification);

alter table certifications
  add primary key using index certifications_pk;

create index certifications_pays_idx
  on certifications
  using btree (pays_code, ordre);


alter table certifications
  add foreign key (pays_code)
    references pays (code);


create table films_certifications (
  film_id integer,
  pays_code text,
  certification text,
  description text
);

alter table films_certifications
  add foreign key (film_id)
    references films on delete cascade;

alter table films_certifications
  add foreign key (pays_code, certification)
    references certifications;

create table votes (
  film_id int not null,
  votants int default 0,
  moyenne decimal not null default 0.0
);

create unique index votes_pkey
  on votes
  using btree (film_id);

alter table votes
  add primary key
  using index votes_pkey;

alter table votes
  add foreign key (film_id)
  references films on delete cascade;


create table user_votes (
  user_id int not null,
  film_id int not null,
  note decimal not null,
  timestamp timestamp with time zone not null
);

create unique index user_votes_pkey
  on user_votes
  using btree (film_id, user_id);

alter table user_votes
  add primary key
  using index user_votes_pkey;


create index vote_film_fki
  on user_votes(film_id);

alter table user_votes
  add constraint vote_film_fk
  foreign key (film_id)
  references films (film_id) match simple
  on update no action
  on delete cascade;

alter table user_votes
  add constraint note_check check (note >= 0 and note < 6) not valid;

CREATE FUNCTION vote_calcul()
  RETURNS trigger
  LANGUAGE 'plpgsql'
AS $BODY$
declare
   moyenne decimal(4,2);
   votants integer;
BEGIN
  SELECT count(*), avg(note) INTO votants, moyenne FROM votes WHERE film_id = NEW.film_id;
  UPDATE votes SET vote_votants=COALESCE(votants,0), vote_moyenne=COALESCE(moyenne,0) WHERE film_id = NEW.film_id;
  RETURN NEW;
END
$BODY$;

create trigger trigger_vote_insert
  after insert
  on user_votes
  for each row
  execute function vote_calcul();

create trigger trigger_vote_update
  after update
  on user_votes
  for each row
  execute function vote_calcul();

create table quizzes (
  quiz_id integer not null,
  quiz text not null,
  questions json not null
);

alter table quizzes
  alter column quiz_id
  add generated by default as identity;

alter table quizzes
  add primary key (quiz_id);

CREATE VIEW personnes_sans_role
 AS
 SELECT p.personne_id,
   p.prenom,
   p.nom,
   count(e.personne_id) AS nb
   FROM personnes p
     LEFT JOIN equipes e ON e.personne_id = p.personne_id
  GROUP BY p.personne_id, p.prenom, p.nom
 HAVING count(e.personne_id) = 0;


CREATE VIEW films_sans_role
 AS
 SELECT f.titre,
   count(e.film_id) AS nb
   FROM films f
     LEFT JOIN equipes e ON e.film_id = f.film_id
  GROUP BY f.titre
 HAVING count(e.film_id) = 0;

create materialized view acteurs as
  select p.personne_id,
  case
    when (p.artiste is not null) then (p.artiste)::text
    else (((p.prenom)::text || ' '::text) || (p.nom)::text)
  end as nom,
  case
    when (p.artiste is not null) then metaphone(p.artiste::text,15)
    else metaphone(((p.prenom)::text || ' '::text) || (p.nom)::text,15)
  end as metaphone,
  p.naissance,
  case
    when (p.deces is null) then date_part('year'::text, age((p.naissance)::timestamp with time zone))
    else null::double precision
  end as age,
  p.deces,
  p.nationalite,
  y.drapeau_unicode,
  count(distinct c.film_id) as nb_film,
  p.popularite
  from (equipes c
    join personnes p on (c.personne_id = p.personne_id)
    left join pays y on p.nationalite = y.code)
  where c.role in ('acteur', 'voix')
  group by p.personne_id, y.drapeau_unicode
  order by popularite desc
with no data;


create view check_films_sans_equipe as
 select f.film_id, f.titre,
    count(e.film_id) as nb
  from films f
    left join equipes e on e.film_id = f.film_id
  group by f.film_id, f.titre
  having count(e.film_id) = 0;

create view check_personnes_sans_role as
 select p.personne_id,
    p.prenom,
    p.nom,
    count(e.personne_id) as nb
  from personnes p
    left join equipes e on e.personne_id = p.personne_id
  group by p.personne_id, p.prenom, p.nom
  having count(e.personne_id) = 0;

create schema tests

create or replace view tests.films_genres_sans_film as
  select fg.film_id,
    fg.genre_id
  from (films_genres fg
    left join films f on fg.film_id = f.film_id)
  where f.film_id = null;


create or replace view view_films_tmdb as  select f.titre,
    f.film_id
   from (films f
     left join links l on (((f.film_id = l.id) and (l.site_id = 1))))
  where (l.id is null);


create or replace view view_personnes_tmdb as  select p.nom,
    p.prenom,
    p.personne_id
   from (personnes p
     left join links l on (((p.personne_id = l.id) and (l.site_id = 1))))
  where (l.id is null);


create or replace view view_nb_films as  select p.nom,
    l.identifiant,
    count(e.film_id) as count
   from ((personnes p
     join equipes e on ((p.personne_id = e.personne_id)))
     left join links l on (((p.personne_id = l.id) and (l.site_id = 1))))
  group by p.nom, l.identifiant;


create or replace view view_films_tmdb as  select f.titre,
    f.film_id
   from (films f
     left join links l on ((f.film_id = l.id) and (l.site_id = 1)))
  where (l.id is null);


create or replace view view_personnes_tmdb as
  select p.nom,
    p.prenom,
    p.personne_id
   from (personnes p
     left join links l on ((p.personne_id = l.id) and (l.site_id = 1)))
  where (l.id is null);

create or replace view view_simili as
SELECT fk1.film_id AS film1,
       fk2.film_id AS film2,
       COUNT(*) AS common_keywords
FROM films_motscles fk1
JOIN films_motscles fk2
  ON fk1.motcle_id = fk2.motcle_id
 AND fk1.film_id < fk2.film_id  -- Assure de ne pas compter les mêmes paires deux fois
GROUP BY fk1.film_id, fk2.film_id
HAVING COUNT(*) > 0
ORDER BY common_keywords DESC;

create function films_with_texte(mot text)
returns table (film_id films.film_id%TYPE
  , titre films.titre%TYPE)
language sql
as $function$
	select f.film_id, f.titre from films f
    inner join resumes r on f.film_id = r.film_id
  where ts @@ to_tsquery('french', mot);
$function$;

create function reco()
  returns table (id films.film_id%TYPE
  ,titre films.titre%type
  ,votants votes.votants%type
  ,moyenne votes.moyenne%type
  ,score float)
  language 'plpgsql'
as $body$
declare
  C float;
  m int;
begin
  select avg(f.vote_moyenne) into C
    from votes f;
  select percentile_disc(0.9) into m
    within group (order by votes.votants)
    from films;
  return query select f.film_id, f.titre, f.votants
  	,f.vote_moyenne
  	,(f.votants::numeric /(f.votants::numeric + m) * f.vote_moyenne) + (m /(f.votants::numeric + m) * C) as score
    from votes f
    where f.votants >= m
    order by score desc
    limit 10;
end
$body$;

create function films_par_acteur (id varchar)
RETURNS TABLE(film_id uuid, titre text, titre_original text,
annee int, sortie date, duree int, votants int, vote_moyenne numeric(4,2), franchise text, alias text[], genres text[], motscles text[], resume text) AS
$$
BEGIN
  return query select f.film_id, f.titre, f.titre_original,
      f.annee, f.sortie, f.duree, f.vote_votants, f.vote_moyenne,
      f2.franchise
      , array_agg(distinct e.alias) as alias
      , array_agg(distinct g.genre) as genres
      , array_agg(distinct mc.motcle) as motscles
      , r.resume
    from films f
    inner join equipes e on e.film_id = f.film_id and e.alias is not null
    left join films_genres fg on fg.film_id = f.film_id
    left join genres g on g.genre_id = fg.genre_id
    left join franchises f2 on f2.franchise_id = f.franchise_id
    left join lateral (SELECT r2.resume FROM resumes r2 WHERE r2.film_id  = f.film_id
      order by array_position(array['deu','fra','eng'], r2.langue_code)
      fetch first 1 row only ) r on true
    left join films_motscles fmc on fmc.film_id = f.film_id
    left join motscles mc on mc.motcle_id = fmc.motcle_id
    where e.personne_id = id::uuid
    group by f.film_id, f.titre, f.titre_original, f2.franchise, f.vote_votants, e.ordre, r.resume
    order by e.ordre, vote_votants desc;
END;
$$
language plpgsql volatile;

create function etablissements_in_view(min_lat float, min_long float, max_lat float, max_long float)
returns table (etablissement_id etablissements.etablissement_id%TYPE
  , nom etablissements.nom%TYPE
	, ville etablissements.ville%TYPE
	, voie etablissements.voie%TYPE
	, codepostal etablissements.codepostal%TYPE
	, lat float, long float)
language sql
as $function$
	select etablissement_id
		, nom
		, ville
		, voie
		, codepostal
		, st_y(coordonnees::geometry) as lat, st_x(coordonnees::geometry) as long
	from etablissements
	where coordonnees OPERATOR(&&) ST_SetSRID(ST_MakeBox2D(ST_Point(min_long, min_lat), ST_Point(max_long, max_lat)), 4326)
$function$;

create temporary table etablissement_tmp
(
  regionCNC smallint,
  nauto integer,
  nom text,
  région_administrative text,
  adresse text,
  code_insee text,
  commune text,
  population text,
  dep text,
  nuu text,
  unité_urbaine text,
  population_unité_urbaine text,
  situation_géographique text,
  écrans smallint,
  fauteuils smallint,
  semaines_activité text,
  séances text,
  entrées_2023 text,
  entrées_2022 text,
  évolution_entrées text,
  tranche_entrées text,
  propriétaire text,
  ae text,
  catégorie_art_et_essai text,
  label_art_et_essai text,
  genre text,
  multiplexe text,
  zone_commune text,
  nombre_films_programmés text,
  nombre_films_inédits text,
  nombre_films_en_semaine_1 text,
  pdm_films_français text,
  pdm_films_américains text,
  pdm_films_européens text,
  pdm_autres_films text,
  films_art_et_essai text,
  part_séances_films_art_et_essai text,
  pdm_films_art_et_essai text,
  latitude float,
  longitude float,
  extra text
);

copy etablissement_tmp
from '/tmp/cinema/cnc-données-cartographie-2023.csv' delimiter ';' csv header quote '"' encoding 'utf8';

insert into etablissements (etablissement_id, nom, voie, ville, ecrans, fauteuils, coordonnees)
  select nauto, nom, adresse, commune, écrans, fauteuils, st_makepoint(longitude, latitude)
  from etablissement_tmp;

drop table etablissement_tmp;

--

copy genres
from '/tmp/cinema/041-genres.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

copy series
from '/tmp/cinema/041-series.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';


copy films (film_id,titre,titre_original,annee,sortie,duree,serie_id, pays)
from '/tmp/cinema/030-films.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

copy films_genres (film_id, genre_id)
from '/tmp/cinema/041-films_genres.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

copy personnes (personne_id, nom, prenom, naissance, deces, nationalite, artiste, popularite)
from '/tmp/cinema/010-personnes.csv' delimiter ',' csv header quote '"' encoding 'utf8';

copy societes
from '/tmp/cinema/011-societes.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

copy equipes from '/tmp/cinema/031-equipes.csv' delimiter ',' csv header quote '"' encoding 'utf8';

copy productions (film_id, societe_id)
from '/tmp/cinema/041-productions.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

copy links_films
from '/tmp/cinema/042-links_films.csv' (format csv, header, encoding 'utf8');

copy links_personnes
from '/tmp/cinema/042-links_personnes.csv' (format csv, header, encoding 'utf8');

copy salles (salle_id, etablissement_id, salle, sieges)
from '/tmp/cinema/043-salles.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

copy resumes (film_id, langue, resume)
from '/tmp/cinema/044-resumes.csv' delimiter ',' csv header quote '"' escape '"' encoding 'utf8';

copy certifications (pays_code,ordre,certification,description)
from '/tmp/cinema/046-certifications.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

-- Mots clés
copy motscles (motcle_id,motcle)
from '/tmp/cinema/030-motscles.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

copy films_motscles (film_id,motcle_id)
from '/tmp/cinema/030-films_motscles.csv' delimiter ',' csv header quote '"' escape '''' encoding 'utf8';

-- Slogans
create temporary table slogan_tmp
(
  film_id int,
  slogan text
);

copy slogan_tmp
from '/tmp/cinema/030-films_slogan.csv' delimiter ',' csv header quote '"' encoding 'utf8';

UPDATE films AS f
SET slogan = t.slogan
FROM slogan_tmp AS t
WHERE f.film_id = t.film_id;



do $$
begin
  for counter in 1..1000 loop
	INSERT INTO seances (film_id, salle_id, seance)
  	VALUES ((SELECT film_id FROM films WHERE random() > 0.9 ORDER BY random() LIMIT 1)
    , (FLOOR(random()*77)+1)
    , (date(now() + trunc(random()  * 14) * '1 day'::interval)+ '21hour'::interval));
  end loop;
end;
$$;

-- https://stackoverflow.com/questions/12618232/copy-a-few-of-the-columns-of-a-csv-file-into-a-table

refresh materialized view acteurs;

-- grant select on all tables in schema public to role_web;

-- https://www.graphile.org/postgraphile/security/

-- PostgREST

grant usage on schema public to guest;
grant usage on schema extensions to guest;

grant select on all tables in schema public
to guest;

-- Extensions installées
select extname, extversion
  from pg_extension;
