-- Crée une nouvelle base nommée cocagne.
create database cocagne;

-- Contrôle l’ordre de résolution des schémas.
alter database cocagne set search_path = public,extensions;

-- Charge automatiquement la bibliothèque anon (PostgreSQL Anonymizer) à l’ouverture de session.
alter database cocagne set session_preload_libraries to 'anon';

-- La modification du paramètre session_preload_libraries s’applique aux nouvelles sessions, une
-- déconnexion et reconnexion est nécessaire pour que les changements soient visibles.

-- Recharger la configuration pour valider les mises à jour du paramètre session_preload_libraries.
select pg_reload_conf();

\pset tuples_only on

-- Active le masquage dynamique transparent pour cette base.
-- Le masquage dynamique :
--   ne modifie pas physiquement les données
--   intercepte les requêtes SELECT
--   applique des règles de masquage selon les privilèges
alter database cocagne set anon.transparent_dynamic_masking to true;

-- Lister les propriétés de la base de données cocagne.
select
  d.datname, r.rolname,
  split_part(cfg, '=', 1) as parameter,
  split_part(cfg, '=', 2) as value
from pg_db_role_setting s
join pg_database d on d.oid = s.setdatabase
left join pg_roles r on r.oid = s.setrole
cross join lateral unnest(s.setconfig) as cfg
where d.datname = 'cocagne';

\c cocagne;

-- Extensions

create schema extensions authorization pg_database_owner;

-- Extension spatiale qui ajoute des types géométriques, index spatiaux et fonctions géographiques.
create extension if not exists postgis schema extensions;

-- Extension qui fournit des opérateurs B-tree compatibles avec les index complexes GiST
create extension if not exists btree_gist schema extensions;

create extension if not exists anon schema extensions;
-- Importe un jeu de données par defaut (iban, nom, ville, etc.).dans les tables du schéma anon.
-- Ces valeurs seront ensuite utilisées lors du processus de pseudonymisation des données.
select anon.init('/tmp/cocagne/postgresql_anonymizer_data_fr_FR');
select anon.version();

create schema if not exists stats authorization pg_database_owner;
create schema if not exists tests authorization pg_database_owner;

-- Liste des schémas
select
  n.nspname as schema,
  r.rolname as owner
from pg_namespace n
join pg_roles r on r.oid = n.nspowner
where nspname not like 'pg_%'
  and nspname <> 'information_schema'
order by n.nspname;

-- Extensions installées
select extname, extversion
  from pg_extension;

-- Données générales
-- --------------------------------------------------------------------------------

create table if not exists banque
(
  swift       text primary key,
  banque      text,
  bic         text,
  agence      text,
  adresse     text,
  code_postal text,
  ville       text
);

create table if not exists pays
(
  code text primary key,
  pays text,
  communautaire boolean  not null default false,
  telephone smallint
);

create temporary table pays_import
(
  code2 text,
  code3 text,
  code_num text,
  pays text,
  drapeau_unicode text,
  forme_longue text,
  independant boolean,
  communautaire boolean,
  telephone smallint
);

copy pays_import
from '/tmp/cocagne/commun/pays.csv' (format csv, header, encoding 'UTF8');

insert into pays
select code2, pays, communautaire, telephone
from pays_import
where independant is true;

create table unite
(
  code text primary key,
  unite text
);

comment on table unite is 'Recommendation no. 20 – Codes for Units of Measure Used in International Trade. https://unece.org/trade/uncefact/cl-recommendations';

select 'Codes officiels géographiques ---------------------';

create table tncc (
  code smallint primary key,
  article text,
  charniere text
);

insert into tncc values
(0,'', 'de'),
(1,'', 'd'''),
(2,'le','du'),
(3,'la','de la'),
(4,'les','des'),
(5,'l''','de l'''),
(6,'aux','des'),
(7,'las','de las'),
(8,'los','de los');

-- Régions

create table region (
  code text primary key,
  region text,
  tncc smallint references tncc,
  cheflieu text
);

create temporary table region_temp
(REG text, CHEFLIEU text, TNCC smallint, NCC text, NCCENR text, LIBELLE text);

copy region_temp
from '/tmp/code_officiel_geographique/v_region_2026.csv' (format csv, header, encoding 'UTF8');

insert into region
select REG, LIBELLE, TNCC, CHEFLIEU from region_temp order by reg;

drop table region_temp;

-- Départements

create table departement (
  code text,
  region_code text,
  departement text,
  tncc smallint references tncc,
  cheflieu text
);

create temporary table departement_temp
(DEP text, REG text, CHEFLIEU text, TNCC smallint, NCC text, NCCENR text, LIBELLE text);

copy departement_temp
from '/tmp/code_officiel_geographique/v_departement_2026.csv' (format csv, header, encoding 'UTF8');

insert into departement
select DEP, REG, LIBELLE, TNCC, CHEFLIEU from departement_temp order by reg;

drop table departement_temp;


create table code_postal (
  id           bigint primary key generated by default as identity,
  code_insee   text,
  cp           text,
  commune      text,
  acheminement text,
  ligne5       text
  --coordonnees  geometry(point, 4326) default null::geometry
);

/*
create index code_postal_coordonnees_idx
  on code_postal
  using gist (coordonnees);
*/

create index
  on code_postal
  using btree (cp);

create index
  on code_postal
  using btree (commune);

create table code_postal_contour (
  cp           text,
  contours     geometry(multipolygon, 4326) default null::geometry
);

create index code_postal_contour_idx
  on code_postal_contour
  using gist (contours);


create table academie (
  code text,
  region text
);

create table canton (
  code text,
  canton text
);

create table epci (
  code text primary key,
  epci text
);

create table commune (
  id integer primary key,
  code_insee text,
  nom_standard text,           -- La Chapelle-du-Châtelard
  nom_sans_pronom text,        -- Chapelle-du-Châtelard
  nom_a text,nom_de text,      -- à Chapelle-du-Châtelard
  nom_sans_accent text,        -- la-chapelle-du-chatelard
  nom_standard_majuscule text, -- LA CHAPELLE-DU-CHÂTELARD
  typecom text,                -- toujours COM
  typecom_texte text,          -- toujours commune
  region text,                 -- code région
  dep_code text,               -- code département
  canton_code text,            -- code canton
  epci_code text,              -- communauté de commune
  academie_code text,          -- code académie
  code_postal text,
  codes_postaux text,
  zone_emploi text,
  code_insee_centre_zone_emploi text,
  code_unite_urbaine text,
  nom_unite_urbaine text,
  taille_unite_urbaine smallint,
  type_commune_unite_urbaine text,
  statut_commune_unite_urbaine text, -- I B C H
  population decimal(10,2),
  superficie_hectare decimal(10,2),
  superficie_km2 decimal(10,2),
  densite decimal(8, 2),
  altitude_moyenne decimal(8,2),
  altitude_minimale decimal(8,2),
  altitude_maximale decimal(8,2),
  mairie geometry(point, 4326) default null::geometry,
  centre geometry(point, 4326) default null::geometry,
  grille_densite smallint,
  grille_densite_texte text,
  niveau_equipements_services smallint,
  niveau_equipements_services_texte text,
  gentile text
);

-- Jardin
-- --------------------------------------------------------------------------------

select 'Jardin ---------------------------------------------------------------';

create table if not exists jardin
(
  id           bigint primary key generated by default as identity,
  jardin       text not null,
  tva          text not null,
  contact      text not null,
  telephone    text not null,
  email        text not null,
  adresse      text not null,
  code_postal  text not null,
  ville        text not null,
  localisation geometry(point, 4326) default null::geometry,
  created_at   timestamp(0) with time zone default current_timestamp not null,
  updated_at   timestamp(0) with time zone default NULL::timestamp(0) with time zone
);

-- Dépôts

create table if not exists depot
(
  id           bigint   primary key generated by default as identity,
  depot        text     not null,
  capacite     smallint not null default 0,
  contact      text,
  telephone    text,
  email        text,
  adresse      text,
  code_postal  text,
  ville        text,
  localisation geometry(point, 4326) default null::geometry,
  actif        boolean  not null default true,
  created_at   timestamp(0) with time zone default current_timestamp not null,
  updated_at   timestamp(0) with time zone default NULL::timestamp(0) with time zone
);

create index depot_localisation_idx
  on depot
  using gist (localisation);

create table armoire
(
  id           bigint   primary key generated by default as identity,
  depot_id     bigint   not null references depot,
  capacite     smallint not null,
  code         text
);

-- Saisons

create table if not exists saison
(
  id           bigint primary key generated by default as identity,
  jardin_id    bigint not null references jardin,
  saison       text   not null,
  date_debut   date   not null,
  date_fin     date   not null,
  periode      daterange generated always as (daterange(date_debut, date_fin, '[]')) stored not null,
  lundi        boolean not null default true,
  mardi        boolean not null default true,
  mercredi     boolean not null default true,
  jeudi        boolean not null default true,
  vendredi     boolean not null default true,
  samedi       boolean not null default false,
  dimanche     boolean not null default false
);

alter table saison
  add constraint saison_check check (date_debut < date_fin);

alter table saison
  add constraint saison_no_overlap exclude using gist (periode with &&);

-- Semaines de fermeture

create table if not exists fermeture
(
  id        bigint   primary key generated by default as identity,
  saison_id bigint   not null references saison on delete cascade,
  semaine   smallint not null check (semaine >= 1 and semaine <= 53),
  constraint fermeture_unique unique (saison_id, semaine)
);

-- Jours fériés

create table ferie
(
  id         bigint generated by default as identity,
  jour       date primary key,
  saison_id  bigint not null references saison on delete cascade,
  ferie      text   not null
);

create or replace function ferie_within_saison_check()
 returns trigger as
$$
declare
    p daterange;
begin
    -- Récupère les dates de la saison liée
    select periode
    into p
    from saison
    where id = NEW.saison_id;

    -- Vérifie l'existence de la saison
    if p is null then
        raise exception 'La saison avec id % est introuvable.', NEW.saison_id;
    end if;

    -- Vérifie que le jour est dans la plage
    if not (NEW.jour <@ p) then
        raise exception 'Le jour férié (%) est en dehors de la saison (%)', NEW.jour, p;
    end if;

    return NEW;
end;
$$ language plpgsql;

create trigger ferie_within_saison_check_trigger
    before insert or update
    on ferie
    for each row
execute function ferie_within_saison_check();

-- Profils

create table if not exists profil
(
  id        bigint primary key generated by default as identity,
  profil    text   not null unique
);

create table if not exists mode_paiement
(
  id            bigint primary key generated by default as identity,
  mode_paiement text     not null,
  nombre        smallint not null default 1,
  actif         boolean  not null default true
);

-- Adhérent
-- --------------------------------------------------------------------------------

create table if not exists adherent
(
  id            bigint primary key generated by default as identity,
  adherent      text   not null,
  profil_id     bigint not null references profil on delete cascade,
  depot_id      bigint          references depot on delete cascade,
  email         text,
  telephone     text,
  date_adhesion date not null default current_date,
  date_sortie   date,
  user_id       bigint,
  adresse       text,
  code_postal   text,
  ville         text,
  localisation  geometry(point, 4326) default null::geometry,
  mode_paiement_id bigint null references mode_paiement,
  domicile      boolean not null default false,
  benevole      boolean not null default false,
  compte_comptable text,
  created_at    timestamp(0) with time zone default current_timestamp not null,
  updated_at    timestamp(0) with time zone default NULL::timestamp(0) with time zone
  constraint adherent_coordonnees_obligatoires_si_domicile
  check ( domicile is not true
    or (
        adresse is not null and btrim(adresse) <> ''
        and code_postal is not null and btrim(code_postal) <> ''
        and ville is not null and btrim(ville) <> ''
    )
  )
);

comment on column adherent.depot_id is 'Dépôt préféré.';

create or replace view stats.adherents with (security_invoker=on) as
select count(a.*) as nb_adherents
from adherent a;

comment on view stats.adherents
  is 'Nombre total d''adhérents';


create or replace view stats.adherents_actifs with (security_invoker=on) as
select count(a.*) as nb_adherents
from adherent a
  where a.date_sortie is null;

comment on view stats.adherents_actifs
  is 'Nombre total d''adhérents actifs.';

-- Cotisation
-- --------------------------------------------------------------------------------

create table if not exists cotisation
(
  id        bigint        primary key generated by default as identity,
  saison_id bigint        not null references saison,
  profil_id bigint        not null references profil on delete cascade,
  montant   numeric(8, 2) not null,
  code      text,
);

comment on table cotisation is 'Montant de la cotisation par saison et par profil';

-- Adhesion

create table if not exists adhesion
(
  id            bigint primary key generated by default as identity,
  adherent_id   bigint not null references adherent on delete cascade,
  date_adhesion date   not null,
  montant       numeric(8, 2) not null,
  saison_id     bigint not null references saison,
  numero        text,
  mode_paiement_id bigint null references mode_paiement,
  created_at    timestamp(0) with time zone default current_timestamp not null,
  constraint adhesion_unique unique (adherent_id, saison_id)
);

-- Produit / Panier

create table if not exists produit
(
  id           bigint        primary key generated by default as identity,
  produit      text          not null,
  prix         numeric(8, 2) not null,
  marge        numeric(8, 2) not null,
  actif        boolean       not null default true,
  ordre        smallint      not null,
  categorie    text,
  couleur      text,
  doublage_id  bigint,
  created_at   timestamp(0) with time zone default current_timestamp not null,
  updated_at   timestamp(0) with time zone default NULL::timestamp(0) with time zone
);

-- Panier

create table if not exists panier
(
  id           bigint   primary key generated by default as identity,
  produit_id   bigint   not null references produit on delete cascade,
  panier       text     not null,
  quantite     smallint not null,
  prix         numeric(8, 2) not null,
  domicile     boolean not null default false,
  actif        boolean not null default true,
  created_at   timestamp(0) with time zone default current_timestamp not null,
  updated_at   timestamp(0) with time zone default NULL::timestamp(0) with time zone
);


-- Calendrier

select 'Calendrier ---------------------------------------------';

create table if not exists calendrier
(
  id             bigint primary key generated by default as identity,
  saison_id      bigint not null,
  calendrier     text   not null
);

-- Planning : Les jours de livraisons possible par calendrier
-- --------------------------------------------------------------------------------

create table if not exists planning
(
  calendrier_id bigint not null references calendrier on delete cascade,
  jour          date   not null,
  primary key (calendrier_id, jour)
);

create or replace function planning_jour_valid()
  returns trigger as
$$
declare
  debut    date;
  fin      date;
  nb_ferie int;
begin
  -- Il doit exister une saison telle que le jour appartient à l’intervalle
  if not exists (
    select 1
    from calendrier c
    join saison s on c.saison_id = s.id
    where c.id = new.calendrier_id
      and new.jour between s.date_debut and s.date_fin
  ) then
    raise exception
      'Le % est invalide pour le calendrier %',
      new.jour, new.calendrier_id;
  end if;

  -- Vérifier que le jour n'est pas un jour férié
  if exists (
    select 1
    from ferie f
    join calendrier c on f.saison_id = c.saison_id
    where c.id = new.calendrier_id
      and f.jour = new.jour
  ) then
    raise exception
      'Le % est un jour férié pour cette saison.',
      new.jour;
  end if;

  -- Vérifier que le jour n'est pas dans une semaine de fermeture
  if exists (
    select 1
    from fermeture f
    join calendrier c on f.saison_id = c.saison_id
    where c.id = new.calendrier_id
      and f.semaine = extract(week from NEW.jour)
  ) then
    raise exception
      'Le % est dans une semaine de fermeture pour cette saison.',
      new.jour;
  end if;

  return NEW;
end;
$$ language plpgsql;

create trigger planning_jour_valid_trigger
  before insert or update
  on planning
  for each row
execute function planning_jour_valid();

--

create view tests.check_planning_ferie
as
select p.*
from planning p
where exists (
  select 1
  from ferie f
  where f.jour = p.jour
);

comment on view tests.check_planning_ferie
  is 'Vérifie qu''un jour du planning n''est pas planifié un jour férié.';

--

create view tests.check_planning_semaine
as
select p.*
from planning p
where exists(
  select 1
  from fermeture f
  join calendrier c on c.id = p.calendrier_id
  where extract(week from p.jour) = f.semaine and f.saison_id = c.saison_id
);

comment on view tests.check_planning_semaine
    is 'Vérifie qu''un jour n''est pas planifié pendant une semaine de fermeture.';

-- Production
-- --------------------------------------------------------------------------------

-- Préparations

create table if not exists preparation
(
  id             bigint   primary key generated by default as identity,
  preparation    text     not null,
  jour           smallint not null
);

comment on table preparation is 'Jour de préparation des tournées';

-- Tournées

create table tournee
(
  id             bigint   primary key generated by default as identity,
  tournee        text,
  preparation_id bigint   not null references preparation,
  calendrier_id  bigint   not null references calendrier,
  ordre          smallint not null,
  couleur        text     not null,
  actif          boolean  not null default true
);

-- Points de livraison

create table if not exists point_distribution
(
    tournee_id     bigint   not null references tournee,
    depot_id       bigint   references depot,
    ordre          smallint not null,
    primary key (tournee_id, depot_id)
);

-- Itinéraire des tournées

create table if not exists itineraire
(
  id             bigint   primary key generated by default as identity,
  tournee_id     bigint   not null references tournee,
  depot_id       bigint   references depot,
  adherent_id    bigint   references adherent,
  ordre          smallint not null,
  constraint     itineraire_ordre unique (tournee_id, ordre),
  constraint     adresse_unique   check  ((depot_id is not null and adherent_id is null) or (depot_id is null and adherent_id is not null))
);

create unique index if not exists uniq_itineraire_tournee_depot
on itineraire(tournee_id, depot_id)
where depot_id is not null;

create unique index if not exists uniq_itineraire_tournee_adherent
on itineraire(tournee_id, adherent_id)
where adherent_id is not null;

comment on table itineraire is 'Itinéraire des points de distribution dans une tournée';
comment on column itineraire.depot_id is 'Le point de distribution est un dépôt.';
comment on column itineraire.adherent_id is 'Le point de distribution est une livraison à domicile chez un adhérent.';

create or replace procedure renumeroter_itineraires_tournee(p_tournee_id bigint)
language plpgsql
as $$
begin
  with numerotation as (
    select
      id,
      row_number() over (
        partition by tournee_id
        order by ordre, id
      ) as new_ordre
    from itineraire
    where tournee_id = p_tournee_id
  )
  update itineraire i
  set ordre = n.new_ordre
  from numerotation n
  where i.id = n.id;
end;
$$;

create table if not exists sync_distribution_log
(
  id                  bigint primary key generated by default as identity,
  started_at          timestamptz not null default now(),
  finished_at         timestamptz,
  created_itineraires integer not null default 0,
  updated_distribution integer not null default 0,
  anomalies           integer not null default 0,
  message             text
);

create or replace procedure synchroniser_distribution_ordre()
language plpgsql
as $$
declare
    v_log_id bigint;
    v_created_itineraires integer := 0;
    v_updated_distribution integer := 0;
    v_anomalies integer := 0;
begin
    -- création entrée log
    insert into sync_distribution_log(message)
    values ('Début synchronisation distribution -> itineraire')
    returning id into v_log_id;


    /*
      1) Création itinéraires manquants (dépôt)
    */
    with manquants as (
        select distinct d.tournee_id, d.depot_id
        from distribution d
        where d.domicile = false
          and d.depot_id is not null
          and not exists (
              select 1
              from itineraire i
              where i.tournee_id = d.tournee_id
                and i.depot_id = d.depot_id
          )
    ),
    max_ordre as (
        select tournee_id, coalesce(max(ordre),0) as max_ordre
        from itineraire
        group by tournee_id
    ),
    a_inserer as (
        select
            m.tournee_id,
            m.depot_id,
            (coalesce(x.max_ordre,0)
             + row_number() over (partition by m.tournee_id order by m.depot_id))::smallint as new_ordre
        from manquants m
        left join max_ordre x on x.tournee_id = m.tournee_id
    )
    insert into itineraire(tournee_id, depot_id, adherent_id, ordre)
    select tournee_id, depot_id, null, new_ordre
    from a_inserer
    on conflict do nothing;

    get diagnostics v_created_itineraires = row_count;


    /*
      2) Création itinéraires manquants (domicile)
    */
    with manquants as (
        select distinct d.tournee_id, d.adherent_id
        from distribution d
        where d.domicile = true
          and d.adherent_id is not null
          and not exists (
              select 1
              from itineraire i
              where i.tournee_id = d.tournee_id
                and i.adherent_id = d.adherent_id
          )
    ),
    max_ordre as (
        select tournee_id, coalesce(max(ordre),0) as max_ordre
        from itineraire
        group by tournee_id
    ),
    a_inserer as (
        select
            m.tournee_id,
            m.adherent_id,
            (coalesce(x.max_ordre,0)
             + row_number() over (partition by m.tournee_id order by m.adherent_id))::smallint as new_ordre
        from manquants m
        left join max_ordre x on x.tournee_id = m.tournee_id
    )
    insert into itineraire(tournee_id, depot_id, adherent_id, ordre)
    select tournee_id, null, adherent_id, new_ordre
    from a_inserer
    on conflict do nothing;

    get diagnostics v_created_itineraires =  row_count;


    /*
      3) Mise à jour distribution.ordre
    */
    update distribution d
    set ordre2 = i.ordre
    from itineraire i
    where i.tournee_id = d.tournee_id
      and (
            (d.domicile = false and i.depot_id = d.depot_id)
         or (d.domicile = true  and i.adherent_id = d.adherent_id)
      );

    get diagnostics v_updated_distribution = row_count;


    /*
      4) Détection anomalies (cas impossibles)
    */
    select count(*)
    into v_anomalies
    from distribution d
    where (d.domicile = false and d.depot_id is null)
       or (d.domicile = true  and d.adherent_id is null);


    /*
      5) Fin log
    */
    update sync_distribution_log
    set finished_at = now(),
        created_itineraires = v_created_itineraires,
        updated_distribution = v_updated_distribution,
        anomalies = v_anomalies,
        message = case
            when v_anomalies > 0
                then 'Terminé avec anomalies (distribution incohérente)'
            else 'Terminé OK'
        end
    where id = v_log_id;

end;
$$;


create view tests.depots_orphan with (security_invoker=on)
  as
select d.id, d.depot
from depot d
left join itineraire d2 on d2.depot_id = d.id
where d2.depot_id is null;

comment on view tests.depots_orphan
  is 'Dépôts sans itineraire (non rattachés à une tournée).';

-- Abonnements
-- --------------------------------------------------------------------------------
create table if not exists abonnement
(
  id               bigint        primary key generated by default as identity,
  adherent_id      bigint        not null references adherent on delete cascade,
  panier_id        bigint        references panier on delete cascade,
  date_debut       date          not null,
  nombre           smallint      not null,
  montant          numeric(8, 2) not null,
  mode_paiement_id bigint        null references mode_paiement,
  saison_id        bigint        null references saison,
  created_at timestamp(0) with time zone default current_timestamp not null,
  updated_at timestamp(0) with time zone default NULL::timestamp(0) with time zone
);

create or replace view adherent_sans_abonnement
--  with (security_invoker=on)
as
select a.*
from adherent a
  left join abonnement b on a.id = b.adherent_id
where b.id is null and (a.date_sortie is null or a.date_sortie > current_date);

create type etat_livraison as enum
(
  'à livrer',
  'préparé',
  'livré',
  'non pris',
  'perdu'
);

create table if not exists livraison
(
  id              bigint         primary key generated by default as identity,
  abonnement_id   bigint         not null references abonnement on delete cascade, -- abonnement -> abonne
  tournee_id      bigint         not null references tournee,
  depot_id        bigint         not null references depot,
  produit_id      bigint         not null references produit,
  qte             smallint       not null default 1,
  livre           etat_livraison not null default 'à livrer',
  calendrier_id   bigint         not null,
  jour            date           not null,
  created_at      timestamp(0) with time zone default current_timestamp not null,
  updated_at      timestamp(0) with time zone default NULL::timestamp(0) with time zone,
  foreign key (calendrier_id, jour) references planning (calendrier_id, jour)
);

create view total_a_produire_semaine as
select
  extract(year from jour) as annee, extract(week from jour) as semaine,
  p.categorie, p.ordre, p.id as produit_id, p.produit, -- produit
  sum(qte)
from livraison l
  join produit p on p.id = l.produit_id
where livre = 'à livrer'
group by annee, semaine, p.id
--order by annee, semaine, categorie, ordre
;

create view total_a_produire_jour_preparation as
select
  extract(year from l.jour) as annee, extract(week from l.jour) as semaine,
  r.id as preparation_id, r.jour, -- jour de préparation
  p.categorie, p.ordre, p.id as produit_id, p.produit, -- produit
  sum(qte)
from livraison l
  join tournee t on t.id = l.tournee_id
  join preparation r on r.id = t.preparation_id
  join produit p on p.id = l.produit_id
where livre = 'à livrer'
group by annee, semaine, r.id, p.id
--order by annee, semaine, r.jour
;

create view total_a_produire_tournee as
select
  extract(year from l.jour) as annee, extract(week from l.jour) as semaine,
  r.id as preparation_id, r.jour, -- jour de préparation
  t.id as tournee_id, t.tournee, -- tournée
  p.id as produit_id, p.produit, -- produit
  sum(qte)
from livraison l
  join tournee t on t.id = l.tournee_id
  join preparation r on r.id = t.preparation_id
  join produit p on p.id = l.produit_id
where livre = 'à livrer'
group by annee, semaine, r.id, p.id, t.id, p.produit
--order by annee, semaine, r.jour, t.id
;

create view total_a_produire_depot as
select
  extract(year from l.jour) as annee, extract(week from l.jour) as semaine,
  r.id as preparation_id, r.jour, -- jour de préparation
  t.id as tournee_id, t.tournee, -- tournée
  o.id as depot_id, o.depot, -- dépôt
  p.id as produit_id, p.produit, -- produit
  sum(qte)
from livraison l
  join tournee t on t.id = l.tournee_id
  join preparation r on r.id = t.preparation_id
  join produit p on p.id = l.produit_id
  join depot o on o.id = l.depot_id
where livre = 'à livrer'
group by annee, semaine, r.id, p.id, t.id, p.produit, o.id
--order by annee, semaine, r.jour, t.id
;

create view tests.depot_sans_livraison as
select
  d.id as depot_id,
  d.depot
from depot d
  left join livraison l on l.depot_id = d.id
where l.id is null;

comment on view tests.depot_sans_livraison
  is 'Dépôt sans livraison.';
-- --------------------------------------------------------------------------------

create table if not exists distribution
(
    id             bigint   primary key generated by default as identity,
    livraison_id   bigint   not null,
    preparation_id bigint   not null,
    tournee_id     bigint   not null references tournee,
    ordre1         smallint not null,
    depot_id       bigint   not null references depot,
    domicile       boolean  not null default false,
    abonnement_id  bigint   not null references abonnement,
    adherent_id    bigint   not null references adherent,
    ordre2         smallint not null,
    calendrier_id  bigint   not null,
    jour           date     not null,
    produit_id     bigint   not null,
    produit        text     not null,
    qte            smallint not null,
    lieu           text     not null,
    adresse        text     not null,
    code_postal    text     not null,
    ville          text     not null,
    localisation   geometry(point, 4326) default null::geometry,
    created_at     timestamp(0) with time zone default current_timestamp not null,
    validated_at   timestamp(0) with time zone default NULL::timestamp(0) with time zone,
    foreign key (calendrier_id, jour) references planning (calendrier_id, jour)
);

--

create table if not exists panier_commande
(
  id           bigint   primary key generated by default as identity,
  preparation_id bigint references preparation,
  produit_id   bigint references produit,
  annee        int not null,
  semaine      smallint not null,
  cible        numeric(8, 2),
  jour         date,
  qte          int,
  montant      numeric(8, 2),
  created_at   timestamp(0) with time zone default current_timestamp not null,
  updated_at   timestamp(0) with time zone default NULL::timestamp(0) with time zone
);

create table if not exists panier_composition
(
  id           bigint   primary key generated by default as identity,
  panier_commande_id    bigint references panier_commande,
  qte          numeric(10, 3) not null,
  montant      numeric(8, 2) not null,
  produit_id   bigint
);

create table if not exists marche_vente
(
  id           bigint   primary key generated by default as identity,
  article_id   bigint,
  qte          numeric(8, 2),
  montant      numeric(6, 2)
);
--

create table if not exists echeance
(
  id              bigint         primary key generated by default as identity,
  jour            date           not null,
  montant         numeric(8, 2)  not null
);

--

create or replace function adherer(_adherent_id bigint, _saison_id bigint)
returns integer
language plpgsql
as $function$
declare
  _adhesion_id integer;
begin

  -- Vérifie si une adhésion existe déjà pour cette saison
  select id
  into _adhesion_id
  from adhesion
  where adherent_id = _adherent_id and saison_id = _saison_id;

  -- Si une adhésion existe déjà, la retourner
  if found then
    return _adhesion_id;
  end if;

  -- Sinon, insérer une nouvelle adhésion
  insert into adhesion (adherent_id, date_adhesion, montant, saison_id, mode_paiement_id)
  select a.id, now(), c.montant, _saison_id, a.mode_paiement_id
  from adherent a
  join cotisation c on c.profil_id = a.profil_id and c.saison_id = _saison_id
  where a.id = _adherent_id
  returning adhesion.id into _adhesion_id;

  -- Retourner la nouvelle adhésion
  return _adhesion_id;
end;
$function$;

--

create table if not exists poste
(
  id            bigint primary key generated by default as identity,
  poste         text   not null
);

create table if not exists employe
(
  id            bigint primary key generated by default as identity,
  prenom        text   not null,
  nom           text   not null,
  service       text,
  poste_id      bigint references poste,
  actif         boolean,
  created_at    timestamp(0) with time zone default current_timestamp not null,
  updated_at    timestamp(0) with time zone default NULL::timestamp(0) with time zone
);

--

create table if not exists don
(
  id            bigint primary key generated by default as identity,
  adherent_id   bigint references adherent,
  montant       numeric(8, 2) not null,
  jour          date not null
);


-- GPAO
-- --------------------------------------------------------------------------------

create table if not exists categorie
(
  id            bigint primary key generated by default as identity,
  categorie     text
);

create table if not exists famille
(
  id            bigint primary key generated by default as identity,
  famille       text
);

create table if not exists article
(
  id                 bigint primary key generated by default as identity,
  article            text not null,
  categorie_id       int references categorie,
  famille_id         int references famille,
  nom_botanique      text,
  caracteristique    text,
  unite              text,
  unit_caisse        text,
  duree_conservation int,
  duree_tempo        int,
  actif              boolean not null default true,
  poids_unitaire     text,
  volume_unitaire    text,
  contenant          int,
  nb_graines         int,
  tri_poids          smallint,
  tri_salissure      smallint,
  conditionnement    text,
  membrane           text,
  recette            text,
  code_vege_produit  bigint,
  fournisseur_id     bigint,
  ref_fournisseur    text,
  tarif_1_fourni     numeric(8,2),
  tarif_2_fourni     numeric(8,2),
  tva_fourn          numeric(4,2),
  origine            text,
  bio                text,
  vente_veg text,
  date_maj date,
  created_at   timestamp(0) with time zone default current_timestamp not null
);

create table article_produit
(
  article_id bigint references article,
  produit_id bigint references article,
  densite numeric(8, 2)
);

--

create table if not exists etape
(
  id            bigint primary key generated by default as identity,
  etape         text not null,
  ordre         smallint
);

create table if not exists action
(
  id            bigint primary key generated by default as identity,
  action        text not null,
  ordre         int,
  etape_id      bigint references etape,
  actif         boolean not null default true,
  utilise       boolean  not null default true,
  categorie_id  bigint,
  sens          smallint not null
);

create table fournisseur
(
  id             bigint primary key generated by default as identity,
  fournisseur    text not null,
  contact        text,
  adresse        text,
  code_postal    text,
  ville          text,
  email          text,
  telephone      text,
  type_article   text,
  categorie      text,
  telephone_contact text,
  reference      text,
  commentaire    text,
  ape            text,
  tva            text,
  iban           text,
  compta         text,
  created_at     timestamp(0) with time zone default current_timestamp not null
);

--

create table fournisseur_prix
(
  id                 uuid default uuidv7() primary key,
  periode            tstzrange not null default tstzrange(current_timestamp, null, '[)') check (not isempty(periode)),
  article_id         bigint references article,
  fournisseur_id     bigint references fournisseur,
  ref_fournisseur    text,
  tarif              numeric(8,2), -- NULL = indisponible
  constraint fournisseur_prix_overlapping_exclusion
    exclude using gist (article_id with =, fournisseur_id with =, periode with &&)
);

create view fournisseur_prix_courant as
select * from fournisseur_prix
where upper_inf(periode);

-- Lors de l'insertion OLD est null

create or replace function fournisseur_prix_historique_insert()
  returns trigger
  language plpgsql
as $$
declare
  v_current fournisseur_prix%rowtype;
begin

  select * into v_current
  from fournisseur_prix
  where article_id     = NEW.article_id
    and fournisseur_id = NEW.fournisseur_id
    and upper_inf(periode);

  -- Si le tarif et la ref n'ont pas changé, on ne fait rien
  if found
    and v_current.tarif           is not distinct from NEW.tarif
    and v_current.ref_fournisseur is not distinct from NEW.ref_fournisseur
  then
    return null;
  end if;

  -- Clôture la ligne courante
  update fournisseur_prix
  set periode = tstzrange(lower(periode), current_timestamp)
  where id = v_current.id;

  -- Insère la nouvelle version
  insert into fournisseur_prix (periode, article_id, fournisseur_id, ref_fournisseur, tarif)
  values (tstzrange(current_timestamp, null), new.article_id, new.fournisseur_id, new.ref_fournisseur, new.tarif);

  return null;
end
$$;

create or replace function fournisseur_prix_historique_update()
  returns trigger
  language plpgsql
as $$
begin

  -- Si le tarif et la ref n'ont pas changé, on ne fait rien
  if    v_current.tarif           is not distinct from NEW.tarif
    and v_current.ref_fournisseur is not distinct from NEW.ref_fournisseur
  then
    return null;
  end if;

  -- Clôture la ligne courante
  update fournisseur_prix
  set periode = tstzrange(lower(periode), current_timestamp)
  where id = OLD.id;

  -- Insère la nouvelle version
  insert into fournisseur_prix (periode, article_id, fournisseur_id, ref_fournisseur, tarif)
  values (tstzrange(current_timestamp, null), new.article_id, new.fournisseur_id, new.ref_fournisseur, new.tarif);

  return null;
end
$$;

-- Le trigger est sur la vue

create trigger fournisseur_prix_trigger_update
instead of update on fournisseur_prix_courant
for each row
execute function fournisseur_prix_historique_update();

create trigger fournisseur_prix_trigger_insert
instead of insert on fournisseur_prix_courant
for each row
execute function fournisseur_prix_historique_insert();
--

create table stock
(
  id            bigint primary key generated by default as identity,
  article_id    bigint,
  materiel_id   bigint,
  fournisseur_id   bigint not null references fournisseur,
  date_entree   date,
  qte           numeric(12, 2),
  unite         text,
  unite_contenant text,
  contenant     text,
  qte_contenant decimal(12,2),
  montant_ht    decimal(8, 2),
  montant_ttc   decimal(8, 2),
  numero        text,
  lot           text,
  zone          text,
  stock         text,
  caracteristique text
);

create table mouvement
(
  id          bigint primary key generated by default as identity,
  stock_id    bigint not null references stock,
  jour        date,
  sens        smallint not null,
  qte         numeric(12, 2) not null,
  created_at  timestamp(0) with time zone default current_timestamp not null
);

create table achat
(
  id           bigint primary key generated by default as identity,
  article_id   bigint,
  qte          numeric(12, 2),
  qte_initiale numeric(12, 2),
  date_livraison date,
  fournisseur_id bigint,
  ref_fournisseur text,
  tarif        numeric(8, 2),
  tva          numeric(4, 2),
  commande     text,
  livre        boolean,
  unite        text,
  unite_contenant numeric(12, 2),
  contenant_id bigint
);

create table plan_culture
(
  id bigint primary key generated by default as identity,
  article_id bigint,
  action_id bigint,
  materiel_id bigint,
  stock bigint,
  plan_palette int,
  memo text,
  main_oeuvre int,
  rendement numeric(8, 3),
  nb_graine int,
  vegetal bigint,
  semaine_debut smallint,
  semaine_fin smallint,
  action2_id bigint,
  rendement2 numeric(8, 3),
  anticipation int,
  hebdomadaire int,
  actif boolean,
  conversion numeric(8, 3),
  created_at    timestamp(0) with time zone default current_timestamp not null,
  updated_at    timestamp(0) with time zone default NULL::timestamp(0) with time zone
);

create table calendrier_culture
(
  id          bigint primary key generated by default as identity,
  produit_id  bigint,
  semaine     smallint,
  culture     smallint
);

create table resistance
(
  code        text primary key,
  type        text,
  resistance  text,
  pathogene   text
);

\dt (public).*

revoke all on schema public from PUBLIC;

grant usage on schema public to cocagne;
grant select, insert, update, delete on all tables in schema public to cocagne;

--
\connect postgres;

select pg_terminate_backend(pg_stat_activity.pid)
  from pg_stat_activity
  where pg_stat_activity.datname = 'cocagne' and pid <> pg_backend_pid();

create database cocagne_test template cocagne;
