### Acteurs
GET http://localhost:8001/acteurs

### Roles
GET http://localhost:8001/equipes?personne_id=eq.3&role=eq.acteur&select=alias,role,films(film_id, titre, annee, duree, genres(*),votes(*))

### Film
http://localhost:8001/films?film_id=eq.11

###
POST http://localhost:8001/rpc/films_par_acteur
Content-Type: application/json

{ "id": 3 }

###
POST http://localhost:8001/rpc/etablissements_in_view
Content-Type: application/json

{ "min_lat": 47.5, "min_long": 6.5, "max_lat": 48.5, "max_long": 7.5 }
