name: pg

services:
  postgresql:
    image: cocagne/pgsql:2026-05
    environment:
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=fr-FR
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-ChangeMe}
    ports:
      - 5432:5432
    networks:
      - pgsql_net
    volumes:
      - data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/tmp

  pgadmin:
    image: dpage/pgadmin4:9.14
    environment:
      PGADMIN_DEFAULT_EMAIL: emmanuel.medina@univ-lorraine.fr
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-ChangeMe}
      PGADMIN_DISABLE_POSTFIX: true
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
    labels:
      - caddy=pgadmin.localhost
      - caddy.reverse_proxy={{upstreams 80}}
      - caddy.tls=internal
    networks:
      - pgsql_net
      - proxy_net
    volumes:
      - admin:/var/lib/pgadmin

  postgrest:
    image: postgrest/postgrest:v14.11
    ports:
      - 8001:8001
    networks:
      - pgsql_net
    environment:
      PGRST_DB_URI: postgres://postgrest:9012@postgresql/cinema
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: guest
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_JWT_CACHE_MAX_LIFETIME: 3600
      PGRST_SERVER_PORT: 8001

  postgraphile:
    build:
      context: ./postgraphile
    ports:
      - 5678:5678
    networks:
      - pgsql_net
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GRAPHILE_ENV: development

networks:
  pgsql_net:
    external: true
  proxy_net:
    external: true

volumes:
  data: {}
  admin: {}

configs:
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "pg",
            "Host": "postgresql",
            "Port": 5432,
            "MaintenanceDB": "${POSTGRES_USER:-postgres}",
            "Username": "${POSTGRES_USER:-postgres}"
          }
        }
      }
