name: pg

services:
  postgresql:
    image: cocagne/pgsql:2026-02
    environment:
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=fr-FR
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-ChangeMe}
    ports:
      - 5432:5432
    networks:
      - pgsql_net
    volumes:
      - data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/tmp

  pgadmin:
    image: dpage/pgadmin4:9.13
    environment:
      PGADMIN_DEFAULT_EMAIL: emmanuel.medina@univ-lorraine.fr
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-ChangeMe}
      PGADMIN_DISABLE_POSTFIX: true
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
    labels:
      - caddy=pgadmin.localhost
      - caddy.reverse_proxy={{upstreams 80}}
      - caddy.tls=internal
    networks:
      - pgsql_net
      - proxy_net
    volumes:
      - admin:/var/lib/pgadmin

networks:
  pgsql_net:
    external: true
  proxy_net:
    external: true

volumes:
  data: {}
  admin: {}

configs:
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
            "Group": "Servers",
            "Name": "pg",
            "Host": "postgresql",
            "Port": 5432,
            "MaintenanceDB": "${POSTGRES_USER:-postgres}",
            "Username": "${POSTGRES_USER:-postgres}"
          }
        }
      }
